export const filtersList = [
  ["isDesk", "Biurko"],
  ["isTeapot", "Czajniczek"],
  ["isEspressoMaker", "Ekspress do kawy"],
  ["isArmchair", "Fotel"],
  ["isSofa", "Sofa"],
  ["isCommode", "Komoda"],
  ["isChairs", "Krzesła"],
  ["isStove", "Kochenka"],
  ["isTableLamp", "Lampa stołowa"],
  ["isRefrigerator", "Lodówka"],
  ["isBed", "Łóżko"],
  ["isMicrowave", "Mikrofalówka"],
  ["isVacuum", "Odkurzacz"],
  ["isOven", "Piekarnik"],
  ["isWindowShade", "Roleta"],
  ["isBedsideTable", "Stolik nocny"],
  ["isTable", "Stół"],
  ["isWardrobe", "Szafa"],
  ["isTV", "Telewizja"],
  ["isBathtub", "Wanna"],
  ["isDishwasher", "Zmywarka"],
  ["isIron", "Żelazko"],
];
